# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 0 * * MON'
env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [v1.x]
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno-version }}
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: deno test --allow-read --allow-env --coverage=coverage
    - run: deno coverage coverage --lcov --output=cov_profile.lcov
    - run: deno task build:npm
    - name: Send coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/cobertura-coverage.xml
