# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 0 * * MON'
env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run coverage
    - name: Send coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/cobertura-coverage.xml
